---
env:
  global:
    - CC_TEST_REPORTER_ID=cc357dcc50da9b6024f1d35f34252fb952ac16de1c0722802e74e851cf1a5d61
sudo: false
language: ruby
cache: bundler
rvm:
  - 2.5.0
  - 2.5.1
  - 2.5.2
  - 2.5.3
  - 2.5.4
  - 2.5.5
  - 2.5.6
  - 2.6.0
  - 2.6.1
  - 2.6.2
  - 2.6.3
  - 2.6.4
before_install: gem install bundler -v 2.0.2
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
